### ISSUE TITLE
CollQuerySerializer uses == operator also when comparing wrapper types

### ISSUE THREAD

**Issue by TuomasKiviaho** [querydsl/querydsl#2350] opened 2018-08-08 09:56 UTC
[Object equality](https://stackoverflow.com/questions/1514910/how-to-properly-compare-two-integers-in-java) should only be used for primitive types and not with wrapper. Hence the `visitOperation` should not be using operator symbols in this case.

``` java
    @Override
    protected void visitOperation(Class<?> type, Operator operator, List<? extends Expression<?>> args) {
        if (Ops.aggOps.contains(operator)) {
            throw new UnsupportedOperationException("Aggregation operators are only supported as single expressions");
        }
        if (args.size() == 2 && OPERATOR_SYMBOLS.containsKey(operator)
             && isPrimitive(args.get(0).getType()) && isPrimitive(args.get(1).getType())) {
            handle(args.get(0));
            append(OPERATOR_SYMBOLS.get(operator));
            handle(args.get(1));
            if (args.get(1) instanceof Constant<?>) {
                append(CAST_SUFFIXES.get(args.get(1).getType()));
            }
            return;
        }

        if (operator == Ops.STRING_CAST) {
            visitCast(operator, args.get(0), String.class);
        } else if (operator == Ops.NUMCAST) {
            @SuppressWarnings("unchecked") //this is the second argument's type
            Constant<Class<?>> rightArg = (Constant<Class<?>>) args.get(1);

            visitCast(operator, args.get(0), rightArg.getConstant());
        } else {
            super.visitOperation(type, operator, args);
        }
    }
```

**Comment by TuomasKiviaho** [comment] 2018-08-08 10:02
As a workaround I am not relying autoboxing and I use operators only with primitive types (that is `args.get(0).getType().isPrimitive() && args.get(1).getType().isPrimitive()`). Autoboxing would fail with the other operators as well if one side is null or when the types can't be compared without casting.

**Comment by jwgmeligmeyling** [comment] 2021-01-01 17:31
You mean in `CollQuerySerializer#visitOperation` correct?

**Comment by jpannier** [comment] 2021-08-20 07:19
@jwgmeligmeyling correct. It is about the wrapping in CollQuerySerializer.

An alternative workaround for the 4.4.0 version is replacing the #WRAPPER_TYPES with an empty set via reflection.

**Comment by jwgmeligmeyling** [comment] 2021-08-20 07:59
Have you tested whether the issue persists on 5.0.0? I think I fixed the issue there, but only closed a duplicate of this issue.

**Comment by jpannier** [comment] 2021-08-20 09:05
> 
> 
> Have you tested whether the issue persists on 5.0.0? I think I fixed the issue there, but only closed a duplicate of this issue.

No, I have not. (Haven't seen the new release ;) )
Just from looking, I would believe that the problem persists as the logic between
4.4. https://github.com/querydsl/querydsl/blob/eb32e3f162a0b7f4ae1dc013bd1eb0d5ea977819/querydsl-collections/src/main/java/com/querydsl/collections/CollQuerySerializer.java#L209 and
5.0 https://github.com/querydsl/querydsl/blob/26f3c89a8a007a9135eb57f095b07e6fc24c516d/querydsl-collections/src/main/java/com/querydsl/collections/CollQuerySerializer.java#L206
 haven't change. Both refer to to the `Primitives` / `PrimitiveUtils` which hasn't changed. 
I could build a test next week.

**Closed** 2023-09-16 21:09 UTC
Labels: waiting-for-feedback, wontfix
