### ISSUE TITLE
Add support GROUP_CONCAT to JPQLTemplates

### ISSUE THREAD

**Issue by CassianoNeves** [querydsl/querydsl#2056] opened 2016-11-23 16:49 UTC
```
QMyEntity qMyEntity = QMyEntity.myEntyti;

SQLExpressions.groupConcat(qMyEntity.myField);
```

When I execute it, the result is 
`unknown operation with operator GROUP_CONCAT`

Looking this previous commit https://github.com/querydsl/querydsl/commit/23e2471b4735ad50f5ac33ad539474d113bb5b07 I notice the JPQLTemplates doesn't support this operation.

**Comment by jwgmeligmeyling** [comment] 2020-05-28 15:19
For SQL use `SQLExpressions.groupConcat`. For JPA this is not supported, because `GROUP_CONCAT` is not a function defined for JPQL. None of the ORM vendors ship it by default, although the function can be registered manually in some cases.

Duplicate of #2020.

**Closed by jwgmeligmeyling** 2020-05-28 15:19 UTC
