### ISSUE TITLE
JPAAnnotationProcessor - Support for incremental annotation processing

### ISSUE THREAD

**Issue by NicklasWallgren** [querydsl/querydsl#2620] opened 2020-06-25 06:14 UTC
Gradle 4.7 provides support for incremental annotation processing.
https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing

It would be nice to see querydsl supporting it.

As of know the **compileQuerydsl** task requires full recompilation every time a class has been changed. Which in my particular case takes 15+ seconds.

```
> Task :compileQuerydsl
Resolving global dependency management for project '<project>'
Excluding []
Custom actions are attached to task ':compileQuerydsl'.
Caching disabled for task ':compileQuerydsl' because:
  Caching has not been enabled for the task
Task ':compileQuerydsl' is not up-to-date because:
  Input property 'stableSources' file <Path>/<File>.java has changed.
Full recompilation is required because com.querydsl.apt.jpa.JPAAnnotationProcessor is not incremental. Analysis took 0.0 secs.
```

```
:compileQuerydsl (Thread[Execution worker for ':',5,main]) completed. Took 17.357 secs.
```

**Comment by piotr-practi** [comment] 2020-07-14 18:42
Note that this was also mentioned in #2380

**Comment by jwgmeligmeyling** [comment] 2020-07-15 11:01
Closing as a duplicate of #2380

**Closed by jwgmeligmeyling** 2020-07-15 11:01 UTC
