### ISSUE TITLE
querydsl update with @Converter

### ISSUE THREAD

**Issue by chans08** [querydsl/querydsl#2785] opened 2021-03-02 10:42 UTC
## Observed vs. expected behavior

I use spring boot 2.4.2 and spring boot dependency manager.
My domain User has userId, password.
And password has a @Converter(converter = Enc.class)

Problem is when I update user, Its Hibernate Update query for userId is set to be encoded password value.

## Steps to reproduce

Create User class has userId, password.
password has a @Converter(converter = Enc.class)
Create querydsl custom impl class with QUser and JPAUpdateClause like below.
>> snippet code
QUser user = QUser.user;
JPAUpdateClause update = update(user).where(user.userId.eq(userId));
update.set(user.password, req.password()) // req.password() value is equal to userId !!
update.execute();
>>

## Environment

Querydsl version: 4.4.0

Querydsl module: com.querydsl:querydsl-core:4.4.0

Database: mysql

JDK: 1.8

## Additional details

Is it share Qdomain property path for equal String value??

**Comment by jwgmeligmeyling** [comment] 2021-03-02 10:47
Converters behave buggy in JPQL anyway, so there is no meaningful way to support it.

See also #2651

Closing as duplicate of #2652

**Closed by jwgmeligmeyling** 2021-03-02 10:47 UTC
Labels: bug
