### ISSUE TITLE
can not create sql like "where (a='1' and ((b=1 and c = 1) or (b=2 and c=3)) )"

### ISSUE THREAD

**Issue by ijiaojian** [querydsl/querydsl#2136] opened 2017-04-26 10:58 UTC
I want to create SQL like "where (a='1' and ((b=1 and c = 1) or (b=2 and c=3)) )" , when I use ExpressionUtils.and method,  the result SQL I get like "where (a='1' and (b=1 and c = 1 or b=2 and c=3) )"

**Comment by Shredder121** [comment] 2017-04-26 11:00
Could you post the code you use to build the query?

**Comment by ijiaojian** [comment] 2017-04-26 11:02
BooleanExpression expression =
		qMerchantOrderSerial.merchantNo.eq(qMerchantSettleAcct.merchantNo)
				.and(qMerchantSettleAcct.merchantNo.eq(parentMerchantNo).or(qMerchantSettleAcct.compPath.like("/"+parentMerchantNo+"%")))
				.and(qMerchantOrderSerial.enterDate.between(settleBegDate, settleEndDate))
				.and(qMerchantOrderSerial.txnType.eq(Constants.MERCHANT_SETTLE_TXN_TYPE_A))
				.and(qMerchantOrderSerial.correct.eq(Constants.NO))
				.and(qMerchantOrderSerial.merCommStatus.eq(Constants.ORDER_SERIAL_STATUS_PRE));

		query.from(qMerchantOrderSerial, qMerchantSettleAcct);

		List<BooleanExpression> predicates = new ArrayList<>();
		for (TmpSettleCalc calc : calcs) {
			if (calc.getGoodsCategory().equals("-1")) {
				predicates.add(qMerchantOrderSerial.productCode.eq(calc.getProductCode()));
			}else {

				predicates.add(
						qMerchantOrderSerial.goodsCategory.eq(calc.getGoodsCategory())
						   .and(qMerchantOrderSerial.productCode.eq(calc.getProductCode()))
				);
			}
		}

		if (!predicates.isEmpty()) {
			BooleanExpression[] tmpPredicate = new BooleanExpression[predicates.size()];
			expression.andAnyOf(predicates.toArray(tmpPredicate));
		}

		query.where(expression);

**Comment by ijiaojian** [comment] 2017-04-26 11:03
`private JPAQuery createJpaquery(String parentMerchantNo, List<TmpSettleCalc> calcs, Date settleBegDate, Date settleEndDate) {
		JPAQuery query = new JPAQuery(em);
		QMerchantOrderSerial qMerchantOrderSerial = QMerchantOrderSerial.merchantOrderSerial;
		QMerchantSettleAcct qMerchantSettleAcct = QMerchantSettleAcct.merchantSettleAcct;

		BooleanExpression expression =
		qMerchantOrderSerial.merchantNo.eq(qMerchantSettleAcct.merchantNo)
				.and(qMerchantSettleAcct.merchantNo.eq(parentMerchantNo).or(qMerchantSettleAcct.compPath.like("/"+parentMerchantNo+"%")))
				.and(qMerchantOrderSerial.enterDate.between(settleBegDate, settleEndDate))
				.and(qMerchantOrderSerial.txnType.eq(Constants.MERCHANT_SETTLE_TXN_TYPE_A))
				.and(qMerchantOrderSerial.correct.eq(Constants.NO))
				.and(qMerchantOrderSerial.merCommStatus.eq(Constants.ORDER_SERIAL_STATUS_PRE));

		query.from(qMerchantOrderSerial, qMerchantSettleAcct);

		List<BooleanExpression> predicates = new ArrayList<>();
		for (TmpSettleCalc calc : calcs) {
			if (calc.getGoodsCategory().equals("-1")) {
				predicates.add(qMerchantOrderSerial.productCode.eq(calc.getProductCode()));
			}else {

				predicates.add(
						qMerchantOrderSerial.goodsCategory.eq(calc.getGoodsCategory())
						   .and(qMerchantOrderSerial.productCode.eq(calc.getProductCode()))
				);
			}
		}

		if (!predicates.isEmpty()) {
			BooleanExpression[] tmpPredicate = new BooleanExpression[predicates.size()];
			expression.andAnyOf(predicates.toArray(tmpPredicate));
		}

		query.where(expression);

		return query;
	}`

**Comment by ijiaojian** [comment] 2017-04-26 11:07
I want each element in predicates  to be linked via "or" ,   like (c=1 and b=2) or (c=2 and c=4)

**Comment by Shredder121** [comment] 2017-04-26 14:38
Oh I see what you mean.
'and' has higher precedence though, so parentheses aren't necessary.
So that's why you don't see them in the query.
```sql
where (a='1' and (b=1 and c = 1 or b=2 and c=3) )
```
and
```sql
where (a='1' and ((b=1 and c = 1) or (b=2 and c=3)) )
```
are identical.

**Comment by jwgmeligmeyling** [comment] 2020-06-04 21:56
Duplicate of #2593.

The expressions are identical. If you really do want the parentheses there, you can do so using a WRAP operation:

```java
Expressions.predicate(Ops.WRAPPED, firstExpression.and(secondExpression))
```

**Closed by jwgmeligmeyling** 2020-06-04 21:56 UTC

**Comment by ijiaojian** [comment] 2020-09-11 07:31
thanks
