### ISSUE TITLE
Necessary to use javax.inject.Provider?

### ISSUE THREAD

**Issue by zvozin** [querydsl/querydsl#2171] opened 2017-07-22 16:27 UTC
E.g. in `HibernateQueryFactory`. 

javax.inject is Java EE, which is usually not around since most people run JRE, not JDK. The dependency isn't declared, either, which necessitates google-hunting the artifact.

If hard dependency on Java 8's `Supplier` is a problem, perhaps a hand-rolled SAM would do?

**Comment by Shredder121** [comment] 2017-07-22 22:38
We depend on `javax.inject:javax.inject` and haven't had issues so far.
Could you double check what the issue is?

**Comment by cowwoc** [comment] 2019-01-25 02:38
As a side-note, `javax.inject` is a problem for Java9+ support: https://github.com/javax-inject/javax-inject/issues/33

**Comment by jwgmeligmeyling** [comment] 2021-01-24 20:45
Fixed in #2709, where `Provider` was switched out with `Supplier`.

**Closed by jwgmeligmeyling** 2021-01-24 20:45 UTC
