### ISSUE TITLE
fetchResults() skip 'group by'

### ISSUE THREAD

**Issue by ThreefLi** [querydsl/querydsl#2378] opened 2018-11-13 09:53 UTC
the generated  count query skip the 'group by' in this case
![image](https://user-images.githubusercontent.com/18640500/48405189-c5740780-e76c-11e8-90fe-cda001284aca.png)
there may be something wrong with this judge:
![image](https://user-images.githubusercontent.com/18640500/48405321-09ffa300-e76d-11e8-8e5f-d9a8ccdc79e5.png)

**Comment by ThreefLi** [comment] 2018-11-13 09:57
it will throw an exception when using having in the page query

**Comment by ThreefLi** [comment] 2018-11-13 09:58
@meatballhat @rocketraman @johnktims @ponzao is it a bug?

**Comment by jwgmeligmeyling** [comment] 2020-05-28 14:38
Its not a bug, the group by clause in the case of `forCountRow` is handled in the code fragment above: https://github.com/querydsl/querydsl/blob/69e74783f0f2e792f1233d2e60c096f93eb39926/querydsl-jpa/src/main/java/com/querydsl/jpa/JPQLSerializer.java#L178-L180

There are limitations of using `fetchResults()` and `fetchCount()` for queries with a having clause however. This is a duplicate of #2053.

**Closed by jwgmeligmeyling** 2020-05-28 14:38 UTC
