### ISSUE TITLE
java.lang.VerifyError: Bad return type with 4.2.0 SQLInsertClause

### ISSUE THREAD

**Issue by balazs-zsoldos** [querydsl/querydsl#2278] opened 2018-03-22 17:10 UTC
If we call the constructor of SQLInsertClause, we get the following error:

    Exception in thread "main" java.lang.VerifyError: Bad return type
    Exception Details:
      Location:
        com/querydsl/sql/dml/AbstractSQLInsertClause.values([Ljava/lang/Object;)Lcom/querydsl/sql/dml/SQLInsertClause; @5: areturn
      Reason:
        Type 'com/querydsl/sql/dml/AbstractSQLInsertClause' (current frame, stack[0]) is not assignable to 'com/querydsl/sql/dml/SQLInsertClause' (from method signature)
      Current Frame:
        bci: @5
        flags: { }
        locals: { 'com/querydsl/sql/dml/AbstractSQLInsertClause', '[Ljava/lang/Object;' }
        stack: { 'com/querydsl/sql/dml/AbstractSQLInsertClause' }
      Bytecode:
        0x0000000: 2a2b b602 74b0

**Comment by Shredder121** [comment] 2018-03-22 17:19
Duplicate of #2275, but thanks so much for reporting.
😅

**Closed by Shredder121** 2018-03-22 17:19 UTC
