### ISSUE TITLE
Not equals generates incorrect query for Solr

### ISSUE THREAD

**Issue by changhiskhan** [querydsl/querydsl#1295] opened 2015-03-31 21:40 UTC
When I write a query like: <field>.ne(<value>), the Lucene query generated is -<field>:<value> +*:*
This does not give any results in Solr, but just the first clause -<field>:<value> does give the correct results as expected. Is this a bug or is there a configuration setting somewhere that needs to be set?

Thanks

**Comment by johnktims** [comment] 2015-05-28 01:48
I haven't been able to reproduce this bug. Would you mind sharing an example of a query that's failing?

Which versions of querydsl, lucene, and solr are you using?

**Comment by johnktims** [comment] 2015-06-12 23:41
I'm closing this because the user hasn't followed up with more details and I can't reproduce the bug. Furthermore we have tests for the bug the user is describing.

If this is still an issue, feel free to reply with additional details and we'll reopen the ticket.

**Closed by johnktims** 2015-06-12 23:41 UTC
