### ISSUE TITLE
"like" and "contains" for UUID fields

### ISSUE THREAD

**Issue by vlsergey** [querydsl/querydsl#2474] opened 2019-09-11 11:12 UTC
Currently UUID fields are backed by ComparablePath<UUID>. It doesn't have like / likeIgnoreCase / contains / etc. string-oriented operations.

There should be a standard way to use contains / like for UUID fields (with string arguments).

**Comment by sumanguduru** [comment] 2020-08-27 01:05
@vlsergey 
Any suggestions how i can use querydsl for UUID contains..?
i mean i have to search for data where UUID contains using query dsl.. any example would be appreciate..

**Comment by jwgmeligmeyling** [comment] 2020-08-27 10:28
Usually UUIDs are mapped to a binairy type / UUID type in the database, which doesn't support these string operations either. Depending on your database mapping you can either treat the expression as String expression (`Expressions.asString((Expression) expression)`) or cast it to a String expression (`Expressions.stringOperation(Ops.STRING_CAST, expression)`).

Closing because this works as intended.

**Closed by jwgmeligmeyling** 2020-08-27 10:28 UTC
