### ISSUE TITLE
How can I compare NumberExpression field with DateTimePath field?

### ISSUE THREAD

**Issue by JadChahine** [querydsl/querydsl#2390] opened 2018-12-04 06:34 UTC
Hi,

I want to make a query in QueryDSL that substract an integer value from a datetime value like the below

Below are the fields

- integer_value: **NumberPath<Integer>**
- status_timestamp: **DateTimePath<java.util.Date>**

The full query

```
select *
from table1 t1
inner join table2 t2 on t2.my_foreign_key = t1.my_primary_key
where t1.status_timestamp > current_date() - 2 * t2.integer_value
```

The part that I need to construct in QueryDSL

`where t1.status_timestamp > current_date() - 2 * t2.integer_value`

Thanks

**Comment by robertandrewbain** [comment] 2018-12-05 21:03
Duplicate of #2389

**Closed** 2018-12-28 00:07 UTC
