### ISSUE TITLE
NotClassFoundError org/geolatte/geom/DimensionalFlag

### ISSUE THREAD

**Issue by mehdichitforoosh** [querydsl/querydsl#2292] opened 2018-04-15 09:22 UTC
Hi.
querydsl-spatial version 4.2.1 dependency in maven get geolatte-geom 1.2.0 that doesn't have DimensionalFlag class used in PGgeometryConverter.
I use SQLQuery<> for query on spatial data on postgres 9.
The Configuration class get PGgeometryType for converting org.postgis.Geometry to org.geolatte.geom.Geometry but has error!!!
```
java.lang.NoClassDefFoundError: org/geolatte/geom/DimensionalFlag
	at com.querydsl.sql.spatial.PGgeometryConverter.convert(PGgeometryConverter.java:179)
	at com.querydsl.sql.spatial.PGgeometryConverter.convert(PGgeometryConverter.java:147)
	at com.querydsl.sql.spatial.PGgeometryType.getValue(PGgeometryType.java:46)
	at com.querydsl.sql.spatial.PGgeometryType.getValue(PGgeometryType.java:29)
	at com.querydsl.sql.Configuration.get(Configuration.java:195)
	at com.querydsl.sql.AbstractSQLQuery.get(AbstractSQLQuery.java:206)
	at com.querydsl.sql.AbstractSQLQuery.newInstance(AbstractSQLQuery.java:560)
```

**Comment by Shredder121** [comment] 2018-04-15 09:55
Do you depend on geolatte?
Sounds like the right jar isn't included.

**Comment by mehdichitforoosh** [comment] 2018-04-15 10:02
@Shredder121 yes.
querydsl-spatial is based on geolatte.

**Comment by mehdichitforoosh** [comment] 2018-04-15 10:08
@Shredder121 
It seems converter should change based on geolatte-geom 1.x version.
https://github.com/GeoLatte/geolatte-geom#redesign-0.x-to-1.0

**Comment by mehdichitforoosh** [comment] 2018-04-16 16:49
PGgeometryConverter based on geolatte-geom 1.2.0 that supports only G2D positions in geometries but 
It can be changed to support G2DM,G3D and G3DM positions in geometries with passing correct CoordinateRefrenceSystem.

`
public class CustomPGgeometryConverter {

    // to postgis

    public static org.postgis.Geometry convert(Geometry geometry) {
        if (geometry instanceof Point) {
            return convert((Point) geometry);
        } else if (geometry instanceof LinearRing) {
            return convert((LinearRing) geometry);
        } else if (geometry instanceof LineString) {
            return convert((LineString) geometry);
        } else if (geometry instanceof MultiLineString) {
            return convert((MultiLineString) geometry);
        } else if (geometry instanceof Polygon) {
            return convert((Polygon) geometry);
        } else if (geometry instanceof MultiPoint) {
            return convert((MultiPoint) geometry);
        } else if (geometry instanceof MultiPolygon) {
            return convert((MultiPolygon) geometry);
        } else if (geometry instanceof GeometryCollection) {
            return convert((GeometryCollection) geometry);
        } else {
            throw new IllegalArgumentException(geometry.getClass().getName());
        }
    }

    private static org.postgis.Point convert(Point point) {
        org.postgis.Point pgPoint = new org.postgis.Point();
        pgPoint.srid = point.getSRID();
        Position position = point.getPosition();
        pgPoint.dimension = position.getCoordinateDimension() > 2 ? 3 : 2;
        pgPoint.haveMeasure = false;

        pgPoint.x = position.getCoordinate(0);
        pgPoint.y = position.getCoordinate(1);
        if (position.getCoordinateDimension() == 3) {
            pgPoint.z = position.getCoordinate(2);
        }
        if (position.getCoordinateDimension() == 4) {
            pgPoint.m = position.getCoordinate(3);
            pgPoint.haveMeasure = true;
        }
        return pgPoint;
    }

    private static org.postgis.Point convert(Position position, int srid) {
        org.postgis.Point pgPoint = new org.postgis.Point();
        pgPoint.srid = srid;
        pgPoint.dimension = position.getCoordinateDimension() == 3 ? 3 : 2;
        pgPoint.haveMeasure = false;

        pgPoint.x = position.getCoordinate(0);
        pgPoint.y = position.getCoordinate(1);
        if (position.getCoordinateDimension() == 3) {
            pgPoint.z = position.getCoordinate(2);
        }
        if (position.getCoordinateDimension() == 4) {
            pgPoint.m = position.getCoordinate(3);
            pgPoint.haveMeasure = true;
        }
        return pgPoint;
    }

    private static org.postgis.Point[] convertPoints(Geometry geometry) {
        org.postgis.Point[] pgPoints = new org.postgis.Point[geometry.getNumPositions()];
        int srid = geometry.getSRID();
        for (int i = 0; i < pgPoints.length; i++) {
            Position position = geometry.getPositionN(i);
            pgPoints[i] = convert(position, srid);
        }
        return pgPoints;
    }

    private static org.postgis.LineString convert(LineString lineString) {
        org.postgis.Point[] pgPoints = convertPoints(lineString);
        org.postgis.LineString pgLineString = new org.postgis.LineString(pgPoints);

//        pgLineString.haveMeasure = lineString.isMeasured();
        pgLineString.setSrid(lineString.getSRID());
        return pgLineString;
    }

    private static org.postgis.LinearRing convert(LinearRing linearRing) {
        org.postgis.Point[] pgPoints = convertPoints(linearRing);
        org.postgis.LinearRing pgLinearRing = new org.postgis.LinearRing(pgPoints);
//        pgLinearRing.haveMeasure = linearRing.isMeasured();
        pgLinearRing.setSrid(linearRing.getSRID());
        return pgLinearRing;
    }

//    private static org.postgis.MultiLineString convert(MultiLineString multiLineString) {
//        org.postgis.LineString[] pgLineStrings = new org.postgis.LineString[multiLineString.getNumGeometries()];
//        for (int i = 0; i < pgLineStrings.length; i++) {
//            pgLineStrings[i] = convert(multiLineString.getGeometryN(i));
//        }
//        org.postgis.MultiLineString pgMultiLineString = new org.postgis.MultiLineString(pgLineStrings);
////        pgMultiLineString.haveMeasure = multiLineString.isMeasured();
//        pgMultiLineString.setSrid(multiLineString.getSRID());
//        return pgMultiLineString;
//    }

    private static org.postgis.Polygon convert(Polygon polygon) {
        int numRings = polygon.getNumInteriorRing();
        org.postgis.LinearRing[] rings = new org.postgis.LinearRing[numRings + 1];
        rings[0] = convert(polygon.getExteriorRing());
        for (int i = 0; i < numRings; i++) {
            rings[i + 1] = convert(polygon.getInteriorRingN(i));
        }
        org.postgis.Polygon pgPolygon = new org.postgis.Polygon(rings);
        pgPolygon.setSrid(polygon.getSRID());
        return pgPolygon;
    }

    private static org.postgis.MultiPoint convert(MultiPoint multiPoint) {
        org.postgis.Point[] pgPoints = convertPoints(multiPoint);
        org.postgis.MultiPoint pgMultiPoint = new org.postgis.MultiPoint(pgPoints);
        pgMultiPoint.setSrid(multiPoint.getSRID());
        return pgMultiPoint;
    }

//    private static org.postgis.MultiPolygon convert(MultiPolygon multiPolygon) {
//        org.postgis.Polygon[] pgPolygons = new org.postgis.Polygon[multiPolygon.getNumGeometries()];
//        for (int i = 0; i < pgPolygons.length; i++) {
//            pgPolygons[i] = convert(multiPolygon.getGeometryN(i));
//        }
//        org.postgis.MultiPolygon pgMultiPolygon = new org.postgis.MultiPolygon(pgPolygons);
//        pgMultiPolygon.setSrid(multiPolygon.getSRID());
//        return pgMultiPolygon;
//    }

    private static org.postgis.GeometryCollection convert(GeometryCollection geometryCollection) {
        org.postgis.Geometry[] pgGeometries = new org.postgis.Geometry[geometryCollection.getNumGeometries()];
        for (int i = 0; i < pgGeometries.length; i++) {
            pgGeometries[i] = convert(geometryCollection.getGeometryN(i));
        }
        org.postgis.GeometryCollection pgGeometryCollection = new org.postgis.GeometryCollection(pgGeometries);
        pgGeometryCollection.setSrid(geometryCollection.getSRID());
        return pgGeometryCollection;
    }

    // to geolatte

    public static Geometry convert(org.postgis.Geometry geometry) {
        switch (geometry.getType()) {
            case org.postgis.Geometry.POINT:
                return convert((org.postgis.Point) geometry);
            case org.postgis.Geometry.LINESTRING:
                return convert((org.postgis.LineString) geometry);
            case org.postgis.Geometry.LINEARRING:
                return convert((org.postgis.LinearRing) geometry);
            case org.postgis.Geometry.POLYGON:
                return convert((org.postgis.Polygon) geometry);
            case org.postgis.Geometry.MULTILINESTRING:
                return convert((org.postgis.MultiLineString) geometry);
            case org.postgis.Geometry.MULTIPOINT:
                return convert((org.postgis.MultiPoint) geometry);
            case org.postgis.Geometry.MULTIPOLYGON:
                return convert((org.postgis.MultiPolygon) geometry);
            case org.postgis.Geometry.GEOMETRYCOLLECTION:
                return convert((org.postgis.GeometryCollection) geometry);
        }
        throw new IllegalArgumentException(geometry.toString());
    }

    private static Point<G2D> convert(org.postgis.Point geometry) {
        int d = geometry.dimension;
        double[] point = new double[d + (geometry.haveMeasure ? 1 : 0)];
        int offset = 0;
        point[offset++] = geometry.x;
        point[offset++] = geometry.y;
        if (d == 3) {
            point[offset++] = geometry.z;
        }
        if (geometry.haveMeasure) {
            point[offset] = geometry.m;
        }
        if (offset == 2) {
            CoordinateReferenceSystem<G2D> referenceSystem = CrsRegistry.getGeographicCoordinateReferenceSystemForEPSG(geometry.srid);
            return Geometries.mkPoint(new G2D(point[0], point[1]), referenceSystem);
        } else if (offset == 3) {
            throw new IllegalStateException("3D point not supported");
        } else if (offset == 4) {
            throw new IllegalStateException("3DM point not supported");
        } else {
            throw new IllegalStateException("point not supported");
        }
    }

    private static PositionSequence<G2D> convertPoints(org.postgis.Point[] points) {
        if (points.length == 0) {
            return Positions.collect(G2D.class);
        }
        G2D[] positions = new G2D[points.length];
        for (int i = 0; i < points.length; i++) {
            Point<G2D> point = convert(points[i]);
            positions[i] = point.getPosition();
        }
        return Positions.collect(G2D.class, positions);
    }

    private static GeometryCollection convert(org.postgis.GeometryCollection geometryCollection) {
        List<Geometry<G2D>> geometries = new ArrayList<>();
        for (int i = 0; i < geometryCollection.numGeoms(); i++) {
           Geometry<G2D> geometry = convert(geometryCollection.getSubGeometry(i));
           geometries.add(geometry);
        }
        return Geometries.mkGeometryCollection(geometries);
    }

    private static MultiPolygon<G2D> convert(org.postgis.MultiPolygon geometry) {
        List<Polygon<G2D>> polygons = new ArrayList<>();
        for (int i = 0; i < geometry.numPolygons(); i++) {
            Polygon<G2D> polygon = convert(geometry.getPolygon(i));
            polygons.add(polygon);
        }
        return Geometries.mkMultiPolygon(polygons);
    }

    private static MultiPoint<G2D> convert(org.postgis.MultiPoint geometry) {
        List<Point<G2D>> points = new ArrayList<>();
        for (int i = 0; i < geometry.numPoints(); i++) {
            Point<G2D> point = convert(geometry.getPoint(i));
            points.add(point);
        }
        return Geometries.mkMultiPoint(points);
    }

    private static MultiLineString convert(org.postgis.MultiLineString geometry) {
        List<LineString<G2D>> lineStrings = new ArrayList<>();
        for (int i = 0; i < geometry.numLines(); i++) {
            LineString<G2D> lineString = convert(geometry.getLine(i));
            lineStrings.add(lineString);
        }
        return Geometries.mkMultiLineString(lineStrings);
    }

    private static Polygon<G2D> convert(org.postgis.Polygon geometry) {
        List<LinearRing<G2D>> rings = new ArrayList<>();
        for (int i = 0; i < geometry.numRings(); i++) {
            LinearRing<G2D> linearRing = convert(geometry.getRing(i));
            rings.add(linearRing);
        }
        return Geometries.mkPolygon(rings);
    }

    private static LinearRing<G2D> convert(org.postgis.LinearRing geometry) {
        PositionSequence<G2D> positionSequence = convertPoints(geometry.getPoints());
        CoordinateReferenceSystem<G2D> referenceSystem = CrsRegistry.getGeographicCoordinateReferenceSystemForEPSG(geometry.srid);
        return Geometries.mkLinearRing(positionSequence, referenceSystem);
    }


    private static LineString<G2D> convert(org.postgis.LineString geometry) {
        PositionSequence<G2D> positionSequence = convertPoints(geometry.getPoints());
        CoordinateReferenceSystem<G2D> referenceSystem = CrsRegistry.getGeographicCoordinateReferenceSystemForEPSG(geometry.srid);
        return Geometries.mkLineString(positionSequence, referenceSystem);
    }

    private CustomPGgeometryConverter() {
    }
}
`

**Comment by ridoo** [comment] 2018-06-14 11:50
I get a similar issue when forcing querydsl to use `geolatte-geom:1.13` (putting the dependency directly in dependencies within the pom.xml). This is the exception I get:

```
java.lang.NoClassDefFoundError: org/geolatte/geom/PolyHedralSurface
	at com.querydsl.sql.codegen.SpatialSupport.registerTypes(SpatialSupport.java:66)
	at com.querydsl.sql.codegen.SpatialSupport.addSupport(SpatialSupport.java:96)
	at org.n52.hbm.codegen.Application.createExporter(Application.java:113)
	at org.n52.hbm.codegen.Application.run(Application.java:109)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at org.n52.hbm.codegen.Application.main(Application.java:48)
Caused by: java.lang.ClassNotFoundException: org.geolatte.geom.PolyHedralSurface
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 common frames omitted
```

Is there any progress in upgrading to newer geolatte version? `0.13` is really old, isn't it? The whole spatial module seems to get unusable when connecting to current spatial database systems.

**Comment by SJean-Marc** [comment] 2020-05-08 18:02
Hi,
Any up about the issue ? For now we can't use querydsl spatial because hibernate spatial use a too recent version of geolatte

**Comment by jwgmeligmeyling** [comment] 2020-12-28 21:55
We're going to upgrade Geolatte together with JTS, so I am closing this as a duplicate of #2404.

**Comment by jwgmeligmeyling** [comment] 2021-01-02 15:38
`querydsl-spatial-sql` only supports Geolatte <= 1.0.0. Due to drastic API changes in Geolatte 1.0.0, `querydsl-spatial-sql` will never support Geolatte 1.x. From now on the `querydsl-spatial-sql` module won't be maintained unless someone steps up to completely rewrite it using Geolatte 1.x or JTS.

**Closed** 2021-01-03 17:59 UTC
Labels: spatial
