### ISSUE TITLE
Entity with multiple constructors annotated with @QueryProjection

### ISSUE THREAD

**Issue by rafaelsj7** [querydsl/querydsl#1647] opened 2015-11-10 13:55 UTC
When annotating multiple constructors, that have same number of parameters, with `@QueryProjection` something goes wrong with constructor usage, for instance:
```java
@Entity
@Table(name = "PERSON")
public class Person {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;
    @Column
    private String  name;
    @ManyToOne
    private Car     car;
    @ManyToOne
    private Address address;

    @QueryProjection
    public Person(Integer id, String name, Car car) {
        this.id = id;
        this.name = name;
        this.car = car;
    }

    @QueryProjection
    public Person(Integer id, Address address, String name) {
        this.id = id;
        this.name = name;
        this.address = address;
    }
    //getters and setters
}
```
The generated sources, regarding Person's constructors, are:
```java
    public static ConstructorExpression<Person> create(Expression<Integer> id, Expression<? extends Address> address, Expression<String> name) {
        return Projections.constructor(Person.class, new Class[]{int.class, Address.class, String.class}, id, address, name);
    }

    public static ConstructorExpression<Person> create(NumberExpression<Integer> id, StringExpression name, QCar car) {
        return Projections.constructor(Person.class, new Class[]{int.class, String.class, Car.class}, id, name, car);
    }
```

Therefore, it's not possible to use an `Expression` to build a `Car` entity, as it follows:
```java
QPerson.create(QPerson.person.id, QPerson.person.name, QCar.create(QPerson.person.car.id, QPerson.person.car.model));
```

**Comment by timowest** [comment] 2015-11-22 20:54
Closing, since this is not a bug, but a design decision in the code generation. Feel free to suggest improvements to the logic.

**Closed by timowest** 2015-11-22 20:54 UTC
