### ISSUE TITLE
Predicate with two filters

### ISSUE THREAD

**Issue by danielfz** [querydsl/querydsl#2616] opened 2020-06-16 17:06 UTC
Is there a way to create a Predicate that filters inner documents by two properties in mongodb?
I'm using such a predicate as an argument to a repository query method.

For example, the following code won't work:
`BooleanBuilder builder = new BooleanBuilder();
builder.and(departmentDocument.employees.any().id.eq("foo"));
builder.and(departmentDocument.employees.any().role.eq("bar"));`

This return true for a department with two employees, each satisfying one of the predicates. I want a department with an employee that satisfies both.

**Comment by johnktims** [comment] 2020-06-23 19:16
I can't reproduce this. I've written a few tests to verify the correct mongodb query is generated and the correct results are returned. Please provide more information about your models.

**Comment by johnktims** [comment] 2020-06-29 03:20
I'm going to close this for now. Follow up with more info and I'll reopen the issue.

**Comment by danielfz** [comment] 2020-06-29 15:53
What were you not able to reproduce? I can see two possible results. The intended behavior might be to:
a) For each "sub-predicate", search for an employee for which it is true, and then return true if all sub-predicates find a corresponding employee.
b) Build a conjunction of all the predicates, and search the employee collection for an element for which the conjunction is true.

The functionality of querydsl would suit my needs if I wanted a). a) works well. But my use case needs b), and I was unable to find how to achieve b) using simple Predicates. I'm guessing that I need to query the database through other means, such as with MongoTemplate, but it would be nice to be able to build a Predicate as the one I explained above.

**Comment by jwgmeligmeyling** [comment] 2021-01-01 17:43
This sounds like a duplicate of https://github.com/querydsl/querydsl/issues/2638#issue-681738472 , could you confirm @danielfz ?

I am about to backport the solution provided in #2689 to the MongoDB serializer, which might resolve this issue.

**Closed** 2022-07-30 16:59 UTC
Labels: mongo, waiting-for-feedback, wontfix
