### ISSUE TITLE
SQL MetaDataExporter with custom sql types

### ISSUE THREAD

**Issue by copierrj** [querydsl/querydsl#1796] opened 2016-02-17 10:56 UTC
I've a use case where I would like the use the PostgreSQL full text support ('tsvector' sql type) within the context of a QueryDSL query.

In order to be able to do this I had to implement the following classes:

- querydsl.TsVector
- querydsl.TsVectorExpression (contains methods to build the expressions we need for our use cases)
- querydsl.TsVectorPath

With these classes I can create every query I need. 

(I'm currently only interested in creating custom expressions on 'tsvector' columns. Selecting, inserting or updating is not required and I'm aware how to implement this in case I do need it.) 

Obviously the code generator of QueryDSL doesn't know about these classes. In order to avoid writing my own metamodel classes by hand I investigated the possibility to have the MetaDataExporter generate classes with fields using the custom TsPath type. I came up with the following:

```java
Connection c = ...;

SQLTemplates templates = new PostgreSQLTemplates();
Configuration configuration = new Configuration(templates);
configuration.registerType("tsvector", querydsl.TsVector.class)

TypeMappings typeMappings = new JavaTypeMappings();
Type type = new ClassType(querydsl.TsVector.class);
typeMappings.register(type, new ClassType(querydsl.TsVector.class, type));

MetaDataExporter exporter = new MetaDataExporter();
exporter.setConfiguration(configuration);
exporter.setTypeMappings(typeMappings);
...
exporter.export(c.getMetaData());
```

This setup results in a metamodel that is very close to what I would like it to be. It results in fields like this:

```java
public final querydsl.TsVectorPath<querydsl.TsVector> tsv = createTsVector("tsv", querydsl.TsVector.class);
```

Unfortunately this doesn't compile because 'createTsVector' doesn't exist. While analyzing the source of the code generator I discovered that this behavior (i.e. expecting these create methods to be available for custom types) is actually hard coded (https://github.com/querydsl/querydsl/blob/master/querydsl-sql-codegen/src/main/java/com/querydsl/sql/codegen/MetaDataSerializer.java#L321).

I figured that in order to get this code compiling, all I had to do was figure out a way to include an 'import static' that brings an appropriate 'creatTsVector' method in scope. The MetaDataExporter doesn't have a setting to include an additional 'import static' but it does have one to include an ordinary 'import' that can be used to trick the code generator into generating a 'static import':

```java
exporter.setImports(new String[]{"static querydsl.factory"});
```

results in:

```java
import static querydsl.factory.*;
```

Which does exactly what I need, provided there is a class named 'querydsl.factory' (with lowercase 'f' to trick the code generator into thinking that I want to import a package, resulting in '.*' to be added) with:

```java
public static <T extends querydsl.TsVector> querydsl.TsVectorPath<T> createTsVector(String var, Class<T> type) {
...
}
```

Although this solution works very well, it does feel like an ugly hack. I've been looking for a better strategy but everything I came up with (e.g. implementing my own Serializer, extending MetaDataExporter or creating a SQLCodegenModule.ENTITYPATH_TYPE like was done to implement spatial support) required a significant amount of additional work.

It would be great if support for using custom database types in the code generator would be easier and fully supported. It would enable me to leverage the power of specialized sql types (there are quite a few of those in the PostgreSQL universe!) without loosing the ability to use QueryDSL to create my queries.

**Comment by timowest** [comment] 2016-02-17 18:17
Thanks for the bug report! This should be fixed in the upcoming release.

**Comment by ieugen** [comment] 2016-02-22 01:54
Hi, 

I am struggling with a very similar issue for about a week now. I'm trying to use custom types (enums and jsons) with PostgreSQL and it seems very difficult to figure out. 

My work-flow is as follows:
- I use gradle flywaydb tasks to clean and apply SQL migrations on the database
- I use the AntMetdadataExporter to generate query types

The problem with this approach is that in order to use custom types I need to have the types and the querydsl types pre-compiled and published since Gradle can't let me depend on one project to build another. 

So I have created a *commons* module to hold the enums and custom types querydsl types and a *database* module to hold the generated qtypes.  I build and publish *commons* and depend on the published version in *database* project in order to generate the Query Types. 

The problems with this approach are:
- commons has to depend on QueryDSL since I need to define the TypeMapping
- complex build process and requirements (chicken and egg)

On top of all that I still haven't managed to do it right :( .

**Comment by copierrj** [comment] 2016-02-22 15:09
Although this it is a different challenge than the one I made this issue for, I'm also a Gradle user and I do know how to cope with your problem.

You write that Gradle don't let you depend on one project to build another. Actually, you can do that. It just requires some additional Groovy magic to make your classes visible to MetdadataExporter.

My setup is as follows:

I've a main project that uses QueryDSL and a submodule (called 'querydsl-tsvector') that contains my custom tsvector extension. 

In my main project I've a configuration that contains everything that should be on the classpath when MetdadataExporter is being executed. I don't use AntMetdadataExporter (don't know if my strategy can be adapted to its use, I expect you can) but I've created my own custom task that calls MetadataExporter:

```groovy
configurations {
  queryDSLMetaDataExporter
}

depencencies {
  ...
  queryDSLMetaDataExporter project(':querydsl-tsvector')
  queryDSLMetaDataExporter 'org.postgresql:postgresql:9.4-1202-jdbc42'

  compile project(':querydsl-tsvector')
  ...
}

task queryDSLGenerateMetadata

// informs Gradle that everything in queryDSLMetaDataExporter should to be build first
queryDSLGenerateMetadata.dependsOn(configurations.queryDSLMetaDataExporter.buildDependencies)

queryDSLGenerateMetadata << {
  // add content of queryDSLMetaDataExporter to classpath
  def loader = GroovyObject.class.classLoader
  configurations.queryDSLMetaDataExporter.each { file ->
    loader.addURL(file.toURL())
  }

  def sql = Sql.newInstance(...)
  def exporter = new MetaDataExporter()
  ...
  exporter.export(sql.getConnection().getMetaData())
}
```

**Comment by ieugen** [comment] 2016-02-22 19:22
Hi @copierrj ,

Thanks for the examples. However I haven't manged to get it working. 

My setup is like fallows:
````
dependencies {
    queryDSLMetaDataExporter project(':commons')
    queryDSLMetaDataExporter sourceSets.main.output
    queryDSLMetaDataExporter "com.querydsl:querydsl-sql:$queryDslVersion"
    queryDSLMetaDataExporter "com.querydsl:querydsl-sql-codegen:$queryDslVersion"
    queryDSLMetaDataExporter "org.postgresql:postgresql:${postgresqlVersion}"
    queryDSLMetaDataExporter "org.slf4j:slf4j-simple:${slf4jVersion}"

    compile project(':commons')
}

task querydslSqlMetadataExport(dependsOn: configurations.queryDSLMetaDataExporter.buildDependencies)

querydslSqlMetadataExport << {
    URLClassLoader loader = GroovyObject.class.getClassLoader()
    configurations.queryDSLMetaDataExporter.each { File file -> loader.addURL(file.toURI().toURL()) }

    SQLTemplates templates = new PostgreSQLTemplates();
    Configuration configuration = new Configuration(templates)

    def communicationType = Class.forName('gr8pi.web.platform.CommunicationType', true, loader) // line 112
    def communicationTypeType = Class.forName('gr8pi.querydsl.CommunicationTypeType', true, loader) // line 113

    configuration.register(communicationTypeType.newInstance())
    configuration.register('communication_tmpls', 'type', communicationType) // line 115

    TypeMappings typeMappings = new JavaTypeMappings()
    Type type = new ClassType(communicationType)
    typeMappings.register(type, new ClassType(communicationTypeType, type))

    def exporter = new MetaDataExporter()

    exporter.setImports(['gr8pi.web.platform', 'gr8pi.querydsl'] as String[]);
    exporter.setPackageName("gr8pi.platform.sql")
    exporter.setTargetFolder(new File(queryDslGenerated))
    exporter.setConfiguration(configuration)
    exporter.setTypeMappings(typeMappings)
....
}
````

And I get 
````
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: groovy.lang.MissingMethodException: No signature of method: com.querydsl.sql.Configuration.register() is applicable for argument types: (gr8pi.querydsl.CommunicationTypeType) values: [gr8pi.querydsl.CommunicationTypeType@5add0cc0]
Possible solutions: register(com.querydsl.sql.types.Type), register(java.lang.String, java.lang.String, com.querydsl.sql.types.Type), register(java.lang.String, java.lang.String, java.lang.Class)
	at build_5o01qqbc6lqg6adfonw1vesce$_run_closure6.doCall(//gr8pi/database/build.gradle:115)
````

I believe the issue is because I'm loading CommunicationTypeType class with another class loader. But If I use *Class.forName('path.to.class')* I get: 

````
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.ClassNotFoundException: gr8pi.web.platform.CommunicationType
	at build_5o01qqbc6lqg6adfonw1vesce$_run_closure6.doCall(/gr8pi/database/build.gradle:112)
````

I'm using gradle 2.11. Any help or working example would be greatly appreciated. I'm slowly loosing my mind over this :( .

**Comment by ieugen** [comment] 2016-02-22 23:01
Hello again, 

The only way I managed to get querydsl to export the metadata with my type was to publish the jar internally and reference it on the buildscript classpath. I didn't mannage to make it work otherwise. 

This is not very good since I need to make a special release of the artifact every time I need to change something. 

````
buildscript {
    dependencies {
        classpath 'gr8pi:commons:1.1.39-3'
}
````

**Comment by copierrj** [comment] 2016-02-23 08:11
Forgot to mention one essential aspect of my solution. I'm using:

```groovy
def loader = GroovyObject.class.classLoader
configurations.queryDSLMetaDataExporter.each { file ->
    loader.addURL(file.toURL())
}

def tsVectorClass = loader.loadClass('nl.idgis.querydsl.TsVector')
```

to load my classes.

**Comment by ieugen** [comment] 2016-02-23 08:19
Thank you. I will try it out. I'm missing some SQL functionality like JSON type support and I think I'm not going to migrate from JPA. I don't have enough time to do the migration. 
Too bad since my application start-up time and internal architecture would have been reduced.

**Comment by ieugen** [comment] 2016-02-23 11:13
@copierrj : Just today we realized we might need full text search capabilities in the project I'm working on. Any chances you can share some code?

**Comment by Shredder121** [comment] 2016-02-23 11:17
You can also have SQL in conjunction with JPA.
We use it in our projects for statistics and aggregations that are not expressible in JPQL.
So you don't have to migrate if you don't want to.

**Comment by ieugen** [comment] 2016-02-23 13:54
@Shredder121 Thanks. I know we don't have to migrate but it is something I wish to do. Because of Hibernate we have a 15s startup time and we have to maintain another layer of mapping and another layer of Repositories. Of course we get some of the features but I think we have benefits of removing that layer completely.

**Closed** 2016-05-15 20:07 UTC
Labels: progress
