### ISSUE TITLE
Support generating field name constants

### ISSUE THREAD

**Issue by yissachar** [querydsl/querydsl#2596] opened 2020-05-28 04:36 UTC
It can often be helpful to reference the actual string value of a particular field. This can be done currently by getting the metadata:

```qUser.firstName.getMetadata().getName()```

However this is verbose and makes the code difficult to read if repeated several times. It would be nice if we could optionally specify that the codegen should generate constants for the field names as well. That way we could instead write:

```qUser.FIRST_NAME```

or similar which would be much more concise.

**Comment by jwgmeligmeyling** [comment] 2020-05-28 11:36
These constants wouldn't really have any function within QueryDSL, so I don't think this is a change that belongs here. Of course making it optional at least prevents it getting in the way of most users, but even then this feature just wouldn't be so relevant and only distract the team. If someone is willing to contribute this: sure, go ahead.

If you're using JPA: keep in mind that JPA's static metamodel (often associated with JPA's own Criteria API) *does* include constants for the field names. You can have JPA's static metamodel alongside QueryDSL's.

There are various APT processors for each of the JPA vendors: https://stackoverflow.com/a/3037817/2104280. For Hibernate, see: https://in.relation.to/2009/11/09/hibernate-static-metamodel-generator-annotation-processor/.

Example metamodel class (from: https://www.baeldung.com/hibernate-criteria-queries-metamodel#static-metamodel)

```java
@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(Student.class)
public abstract class Student_ {
 
    public static volatile SingularAttribute<Student, String> firstName;
    public static volatile SingularAttribute<Student, String> lastName;
    public static volatile SingularAttribute<Student, Integer> id;
    public static volatile SingularAttribute<Student, Integer> gradYear;
 
    public static final String FIRST_NAME = "firstName";
    public static final String LAST_NAME = "lastName";
    public static final String ID = "id";
    public static final String GRAD_YEAR = "gradYear";
}
```

**Comment by yissachar** [comment] 2020-05-29 00:31
Thanks for the quick response. We are using Spring Data + QueryDSL + Mongo. Unfortunately, Spring Data doesn't currently support delete or update operations with QueryDSL so we still have to write those with raw Mongo operations. We are using the QueryDSL metadata to at least give us some safety with the field names, even though we obviously don't get type safety or any of the other QueryDSL features.

I figured this might have wider applicability outside of our use case, but given your response it seems that isn't the case. I'll try to take a look at what's involved in adding data modification capabilities to Spring Data QueryDSL - if that is properly supported we don't have any need for this.

**Comment by jwgmeligmeyling** [comment] 2020-05-31 22:23
Thats actually a valid use case then, because the JPA metamodel is no viable alternative when using MongoDB 😄 

I noticed it also has been reported before.

Closing as a duplicate of #2083, for which by the way an implementation is proposed in #2084.

**Closed by jwgmeligmeyling** 2020-05-31 22:23 UTC
Labels: feature
