### ISSUE TITLE
SBT support, META-INF/services is not included in final build of querydsl-jpa

### ISSUE THREAD

**Issue by cranberrysoft** [querydsl/querydsl#2376] opened 2018-11-04 03:41 UTC
Currently it is not possible to easily use Querydsl with SBT. I would like to ask what is the reason why 
javax.annotation.processing.Processor is not included in querydsl-jpa so that SBT could run it automatically. 
I built wrapper for querydsl-jpa with my own processor which extends the com.querydsl.apt.jpa.JPAAnnotationProcessor and it works perfectly ok with SBT. 

I don't understand why META-INF/services is not included to final built of querydsl-jpa ?

**Comment by Adrodoc** [comment] 2019-03-22 15:14
Duplicate of #437?

**Comment by jwgmeligmeyling** [comment] 2020-10-14 15:31
Seems like it. You have to specify the `jpa` classifier. In SBT, this can be done as such: https://stackoverflow.com/a/18579444/2104280

**Closed by jwgmeligmeyling** 2020-10-14 15:31 UTC
Labels: jpa
