### ISSUE TITLE
fetchResults or fetchCount show errors,but fetch work ,when i use group by aggregate function

### ISSUE THREAD

**Issue by AINewBegin** [querydsl/querydsl#2591] opened 2020-05-26 15:23 UTC
i find HqlBaseParser cant parser the aggregate function  such as YEAR by debug source code

i find that there no this token by serach it in file.

MY CODE
```
        StringTemplate strDate = Expressions.stringTemplate("YEAR({0})", qUser.date);
        StringTemplate moneySum = Expressions.stringTemplate("SUM({0})", qUser.money);
        jpaQueryFactory.select(moneySum, strDate).from(qUser).groupBy(strDate).fetchResults();
```
SQL LOG:
```
        org.hibernate.hql.internal.ast.QuerySyntaxException: expecting CLOSE, found '(' near line 1, column 27 [select count(distinct YEAR(user.date)) from glf.ainewbegin.japquerylearn.dao.User user]
```

**Comment by jwgmeligmeyling** [comment] 2020-05-28 13:23
I think the result is that a count query can't be generated for a query that already has aggregation functions in it. Could you try with `fetch()` instead of `fetchResults()`?

**Comment by jwgmeligmeyling** [comment] 2020-05-28 14:34
Duplicate of #2053

**Closed by jwgmeligmeyling** 2020-05-28 14:34 UTC

**Comment by jwgmeligmeyling** [comment] 2020-05-31 21:22
Actually more a duplicate of #2504
