### ISSUE TITLE
com.querydsl.core.types.dsl.ComparableExpression.lt is Final

### ISSUE THREAD

**Issue by cbriarnold** [querydsl/querydsl#2302] opened 2018-05-01 13:32 UTC
I assume this was not intentional, since com.querydsl.core.types.dsl.ComparableExpression.gt is not Final. But when I was mocking this for some unit testing, the finality of the 'lt' method made it so that it was not mockable.

**Comment by jwgmeligmeyling** [comment] 2020-10-14 15:44
Duplicate of https://github.com/querydsl/querydsl/issues/2564

**Closed by jwgmeligmeyling** 2020-10-14 15:44 UTC
