### ISSUE TITLE
querydsl-collections: Evaluator compilation failure

### ISSUE THREAD

**Issue by jotak** [querydsl/querydsl#1262] opened 2015-03-16 14:41 UTC
As discussed on groups here: https://groups.google.com/forum/#!topic/querydsl/NPrkWsoq-iM

The generated code compilation fails when we use guava's Optional, or more generally when using some non public class (like com.google.common.base.Present implicitely used through Optional).

Reproduction steps: just run the given gist https://gist.github.com/jotak/54e46b022f6b700a5f91

        Error: 
        Exception in thread "main" com.mysema.codegen.CodegenException: Compilation of public class Q_0390602011_1275614662_1275614662_566403833 {
    
        public static Iterable<cat.Cat> eval(Iterable<cat.Cat> cat_, com.google.common.base.Present a1) {
            java.util.List<cat.Cat> rv = new java.util.ArrayList<cat.Cat>();
            for (cat.Cat cat : cat_) {
                try {
                    if (com.mysema.query.collections.CollQueryFunctions.equals(cat.getPedigree(), a1)) {
                        rv.add(cat);
                    }
                } catch (NullPointerException npe) { }
            }
            return rv;    }
    
    }
    
    failed.
            /Q_0390602011_1275614662_1275614662_566403833.java:3: error: Present is not public in com.google.common.base; cannot be accessed from outside package
    public static Iterable<cat.Cat> eval(Iterable<cat.Cat> cat_, com.google.common.base.Present a1) {
            ^
            1 error
    
            at com.mysema.codegen.JDKEvaluatorFactory.compile(JDKEvaluatorFactory.java:74)
            at com.mysema.codegen.AbstractEvaluatorFactory.createEvaluator(AbstractEvaluatorFactory.java:128)

As said in groups post, it looks like the signature of the generated "eval" method is wrong, as it uses a non accessible class "com.google.common.base.Present" instead of its base class Optional. Maybe the signature generation should look for the first public class in ancestors?

By the way, do you see any workaround for me, so I can use Optional fields?

I'm using querydsl 3.3.3, I tried with the latest (3.6.2) but the issue is still there.

Thanks

JT

**Comment by Shredder121** [comment] 2015-03-17 09:14
This issue is divided into two parts, where I think one part is mandatory.

- Traverse superclasses until a visible one is found (is in my opinion very useful)
- Add Optional support

**Comment by Shredder121** [comment] 2015-03-19 12:33
Optional support is maybe not necessary, since the equals contract of Optional is already well defined. It is only equal if it they are both the same implementation (Absent or Present) and the instances contained are equal(inapplicable for Absent).
As for the non public classes, I already pushed some optimalizations to querydsl/codegen#23 and I can confirm that for this test case it works.

**Comment by jotak** [comment] 2015-03-19 17:34
Yes, I guess there's no special case to implement for Optional. Thanks!
Do you know when it can be released?

**Comment by Shredder121** [comment] 2015-03-26 21:10
This depends on querydsl/codegen#23, so in theory after that is merged we can import that fix so that #1265 will pass.

**Closed** 2015-04-01 10:29 UTC

**Comment by jotak** [comment] 2015-04-08 08:10
it works perfectly, thanks!
