### ISSUE TITLE
Projections.bean' s problem

### ISSUE THREAD

**Issue by lyxaaadf** [querydsl/querydsl#2569] opened 2020-04-17 09:32 UTC
=======>see
Projections.bean(PracticeSentimentVo.class,
  		 							qPracticeSentiment.id,
  		 							qUser.id.as("uId"),
  		 			                qUser.name,
  		 			                qUser.avatar,
  		 			                qPracticeSentiment.content.as("sentimentContent"),
  		 			                qPracticeSentiment.createTime,

=========================
I use Projections.bean that
 qUser.id.as("uId"), but the result is NULL ，yes，for uId;but if use  qUser.id.as("uid") that  has value.

when I use  Projections.filelds and qUser.id.as("uId"), this uId have value

why???
Principle of hump?

Complete SQL==============》

- Complete SQL
<pre>
List<PracticeSentimentVo> list = jpaQueryFactory
                 .from(qPracticeSentiment)
                 .leftJoin(qUser).on(qPracticeSentiment.studentId.eq(qUser.id))
                 .leftJoin(qPracticeSentimentAttach).on(qPracticeSentiment.id.eq(qPracticeSentimentAttach.pid))
                 .where(
                         qPracticeSentiment.activityStudentId.in(activityStudent)
                 )
                 .orderBy(qPracticeSentiment.createTime.desc())
                 .transform(
  		 			GroupBy.groupBy(qPracticeSentiment.id).list(
  		 					Projections.fields(PracticeSentimentVo.class,
  		 							qPracticeSentiment.id,
  		 							qUser.id.as("uId"),
  		 			                qUser.name,
  		 			                qUser.avatar,
  		 			                qPracticeSentiment.content.as("sentimentContent"),
  		 			                qPracticeSentiment.createTime,
  		 			                GroupBy.list(
  		 			                		Projections.bean(
  		 			                				PracticeSentimentAttachVo.class,
  		 			                				qPracticeSentimentAttach.id,
  		 			                				qPracticeSentimentAttach.pic
  		 			                				)).as("practiceSentimentAttachVos")
  	 		 				)	
  		 					
  		 			)
                 );
</pre>

**Comment by jwgmeligmeyling** [comment] 2021-02-25 13:35
Closing as a duplicate of #1794

**Closed by jwgmeligmeyling** 2021-02-25 13:35 UTC
Labels: question
