### ISSUE TITLE
querydsl-collections orderBy() fails on null elements

### ISSUE THREAD

**Issue by harshtuna** [querydsl/querydsl#2107] opened 2017-02-22 02:36 UTC
com.querydsl.collections.MultiComparator#compare

maybe use `instenceof` here
```
    @Override
    public int compare(T o1, T o2) {
        if (o1.getClass().isArray()) {
```

**Comment by jwgmeligmeyling** [comment] 2021-06-03 15:23
Closed as duplicate of #2106  (which has already been fixed)

**Closed by jwgmeligmeyling** 2021-06-03 15:23 UTC
Labels: wontfix
