### ISSUE TITLE
how to use group_concat in queryDSL?

### ISSUE THREAD

**Issue by powek** [querydsl/querydsl#2192] opened 2017-08-26 02:22 UTC
i just to use querydsl in my project, there is my problerm that i don't know how to use group_concat in queryDSL,.

  may someone help me ?  thanks!

**Comment by kevzz81517** [comment] 2019-01-16 11:08
import sql dependency.
use SQLExpressions.groupConcat()

**Comment by jwgmeligmeyling** [comment] 2020-05-28 15:12
For SQL use `SQLExpressions.groupConcat`. For JPA this is not supported, because `GROUP_COPONCAT` is not a function defined for JPQL. None of the ORM vendors ship it by default, although the function can be registered manually in some cases. Duplicate of  #2192.

**Comment by jwgmeligmeyling** [comment] 2020-05-28 15:12
Duplicate of #2192.

**Comment by jwgmeligmeyling** [comment] 2020-05-28 15:13
Duplicates #2056

**Closed by jwgmeligmeyling** 2020-05-28 15:12 UTC

**Comment by jwgmeligmeyling** [comment] 2020-05-28 15:18
Duplicate of #2020.
