### ISSUE TITLE
querydsl-jpa paging query the total number is 1，result is 0

### ISSUE THREAD

**Issue by Little0Sheep** [querydsl/querydsl#2626] opened 2020-07-15 14:13 UTC
Please see the picture below

![image](https://user-images.githubusercontent.com/23427472/87555582-390bac00-c6e8-11ea-8728-32eda1fae40c.png)

why is this

The same is true for the pagination query of jpa

Only the pagination query results of mybatis are displayed normally

**Comment by jwgmeligmeyling** [comment] 2020-07-16 12:34
Pagination is fundamentally broken in JPA. See also the ongoing discussion in PR https://github.com/querydsl/querydsl/pull/2605 .

Please use `fetch().size()` for reliable results.

**Comment by jwgmeligmeyling** [comment] 2020-07-16 12:35
Duplicate of #2504 and #2053.

**Closed by jwgmeligmeyling** 2020-07-16 12:34 UTC
